# Customer Support Agent — Evaluation, LangSmith Observability & OpenTelemetry

**Goal:** Build a small e-commerce customer support agent with **LangGraph**, trace every run in **LangSmith**, and learn how to evaluate it like a real ML system.

By the end of this notebook you will have:
1. A LangGraph agent that classifies support tickets into clear categories
2. A synthetic ticket dataset with ground-truth labels
3. LangSmith traces for every prediction (clickable in the UI), emitted through OpenTelemetry
4. Accuracy / precision / recall metrics
5. A CSV of results you can open in a spreadsheet and annotate
6. A simple loop: **inspect failures → tweak the prompt → re-run → compare**

---

## The workflow you'll follow

1. **Run the agent** on the synthetic tickets.
2. **Look at the metrics** and open the exported CSV in Google Sheets / Excel.
3. **Add validator comments** in the `validator_comment` column — flag anything that looks wrong, ambiguous, or surprising.
4. **Cluster the failures** into 2–4 *failure categories* (e.g., "misroutes complaints as questions", "confuses refund vs. return").
5. **Pick the one failure category that matters most** for your use case.
6. **Tweak the classifier prompt** at the bottom of the notebook to address it.
7. **Re-run** the agent and compare the new metrics + LangSmith/OpenTelemetry traces.

## 1. Install dependencies

In [1]:
%pip install --quiet langgraph "langsmith[otel]>=0.4.25" langchain-openai langchain-core pandas scikit-learn pydantic tqdm opentelemetry-sdk opentelemetry-exporter-otlp

Note: you may need to restart the kernel to use updated packages.

## 2. Set up API keys, LangSmith tracing, and OpenTelemetry

You need two keys:
- **`OPENAI_API_KEY`** — get one at [platform.openai.com/api-keys](https://platform.openai.com/api-keys)
- **`LANGSMITH_API_KEY`** — get one at [smith.langchain.com](https://smith.langchain.com) → Settings → API Keys

Once these are set, every LLM call is traced in LangSmith. We also enable OpenTelemetry so each ticket-level eval run can carry standard span metadata like ticket id, prompt version, expected label, predicted label, and correctness.

In [2]:
import os
import getpass
from pathlib import Path

# Clear stale tracing variables so an old endpoint does not make OTel export to a 404 URL.
for k in [
    "LANGCHAIN_API_KEY",
    "LANGCHAIN_ENDPOINT",
    "LANGCHAIN_TRACING_V2",
    "OTEL_EXPORTER_OTLP_ENDPOINT",
    "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
    "OTEL_EXPORTER_OTLP_HEADERS",
    "OTEL_EXPORTER_OTLP_TRACES_HEADERS",
    "OTEL_EXPORTER_OTLP_PROTOCOL",
]:
    os.environ.pop(k, None)

def _load_dotenv(path: str) -> dict:
    """Parse a simple KEY=VALUE .env file. Returns {} if the file doesn't exist."""
    env_path = Path(path)
    if not env_path.exists():
        return {}
    values = {}
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values

_dotenv = _load_dotenv(".env.demo")

def _set(key: str, prompt: str):
    # .env.demo always wins over a stale value left in os.environ by an earlier
    # kernel run, so rotating the key in .env.demo takes effect without a kernel restart.
    if _dotenv.get(key):
        os.environ[key] = _dotenv[key]
    elif not os.environ.get(key):
        os.environ[key] = getpass.getpass(prompt)

_set("OPENAI_API_KEY",    "OpenAI API key: ")
_set("LANGSMITH_API_KEY", "LangSmith API key: ")

# LangSmith is still the evaluation/debugging UI.
os.environ["LANGSMITH_TRACING"]  = "true"
os.environ["LANGSMITH_PROJECT"]  = "customer-support-evals"
os.environ["LANGSMITH_ENDPOINT"] = "https://api.smith.langchain.com"  # use https://eu.api.smith.langchain.com for EU accounts

# OpenTelemetry is the standard tracing layer. LangSmith receives the emitted spans.
os.environ["LANGSMITH_OTEL_ENABLED"] = "true"
os.environ["OTEL_SERVICE_NAME"] = "customer-support-evals-notebook"
os.environ["OTEL_EXPORTER_OTLP_ENDPOINT"] = "https://api.smith.langchain.com/otel"
os.environ["OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"] = "https://api.smith.langchain.com/otel/v1/traces"
os.environ["OTEL_EXPORTER_OTLP_PROTOCOL"] = "http/protobuf"

otel_headers = f"x-api-key={os.environ['LANGSMITH_API_KEY']},Langsmith-Project={os.environ['LANGSMITH_PROJECT']}"
os.environ["OTEL_EXPORTER_OTLP_HEADERS"] = otel_headers
os.environ["OTEL_EXPORTER_OTLP_TRACES_HEADERS"] = otel_headers

print("Traces will appear in LangSmith project:", os.environ["LANGSMITH_PROJECT"])
print("OpenTelemetry service name:", os.environ["OTEL_SERVICE_NAME"])
print("OpenTelemetry traces endpoint:", os.environ["OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"])

Traces will appear in LangSmith project: customer-support-evals
OpenTelemetry service name: customer-support-evals-notebook
OpenTelemetry traces endpoint: https://api.smith.langchain.com/otel/v1/traces

## 3. Define the ticket categories

We keep the label space small and unambiguous on purpose — when there are 50 categories, *everything* looks like a model failure. Five is a good teaching size.

| Category | What belongs here |
|---|---|
| `order_status` | "Where is my order?", tracking, delivery ETA |
| `refund_request` | Customer wants money back, return-for-refund |
| `product_issue` | Item arrived broken, wrong, defective, or not as described |
| `account_help` | Login, password, address, payment method changes |
| `other` | Anything that doesn't fit above (general questions, feedback) |

In [3]:
CATEGORIES = [
    "order_status",
    "refund_request",
    "product_issue",
    "account_help",
    "other",
]

## 4. Load the golden ticket dataset

This dataset is pulled directly from the course evaluation worksheet
(https://docs.google.com/spreadsheets/d/1MVIxuy2C6FNDcDVEgmZjV_LqX9Fd4rCRbpv2qRabeSY) —
150 tickets, each with a human-assigned `true_category`. Using this fixed, pre-labeled
set (instead of generating fresh synthetic paraphrases each run) means the `true_category`
column here matches exactly what Step 1-3 of that worksheet used to annotate and cluster
classifier failures, so prompt changes can be checked against the same ground truth.

In [4]:
# Golden ticket dataset — pulled directly from the course evaluation worksheet
# (https://docs.google.com/spreadsheets/d/1MVIxuy2C6FNDcDVEgmZjV_LqX9Fd4rCRbpv2qRabeSY),
# so every row's true_category matches what Step 1-3 of that worksheet used to grade failures.
GOLDEN_TICKETS = [
    ("Hi, I ordered a blender 5 days ago and the tracking page hasn't updated. Can you tell me where it is?", "order_status"),
    ("Hey, placed an order for a blender 5 days back and the tracking still shows nothing. Where is it?", "order_status"),
    ("So I ordered a blender on Monday, supposedly it shipped, but the tracking page is dead. What's going on?", "order_status"),
    ("My package was supposed to arrive yesterday but it's still not here. Order #44812.", "order_status"),
    ("Order #44812 was due yesterday and hasn't shown up. Any update?", "order_status"),
    ("Where's my package? Was supposed to arrive yesterday — order #44812 if that helps.", "order_status"),
    ("Tracking link in the email just spins forever. Order #88421.", "order_status"),
    ("Hey, the tracking link you emailed me for order 88421 doesn't load — just keeps spinning. Help?", "order_status"),
    ("Tracking URL is broken. Order 88421. Can you tell me where the package is?", "order_status"),
    ("Order shows delivered last Tuesday but it's not at my door, my neighbor's, or the mailroom. What now?", "order_status"),
    ("My order is marked delivered as of last Tuesday but it's nowhere to be found. Help.", "order_status"),
    ("Says delivered Tuesday — checked the porch, the neighbors, the mailroom. Nothing. What do I do?", "order_status"),
    ("I never received my order and I want my money back.", "refund_request"),
    ("I haven't received my order yet — please refund me.", "refund_request"),
    ("Still no package. I want a refund.", "refund_request"),
    ("Order shows delivered but I never got it. Refund please.", "refund_request"),
    ("Package says delivered but I don't have it. I'd like a refund.", "refund_request"),
    ("Marked as delivered, I never got it. Just refund me at this point.", "refund_request"),
    ("The website said 2-day shipping. It's been 9 days. Are you kidding me?", "order_status"),
    ("Promised 2-day delivery. Day nine. This is a joke.", "order_status"),
    ("You advertised 2-day shipping. Where is my order? It's been more than a week.", "order_status"),
    ("My item has been stuck in customs for 3 weeks. What can you do?", "order_status"),
    ("Customs has been holding my order for three weeks. Any way to speed this up?", "order_status"),
    ("It's been 21 days in customs. I need an update on when this will arrive.", "order_status"),
    ("The carrier marked it delivered but it shows the wrong delivery address.", "order_status"),
    ("Carrier delivered to the wrong address. The address on the label is not mine.", "order_status"),
    ("Order was sent to an address I don't recognize and now it's gone. What happened?", "order_status"),
    ("Where exactly is order #50221? I need it for my wedding tomorrow.", "order_status"),
    ("Order #50221 is for my wedding tomorrow. Where is it??", "order_status"),
    ("Wedding is tomorrow and order 50221 still hasn't arrived. Please help.", "order_status"),
    ("I'd like to return the headphones I bought last week and get my money back. They're unopened.", "refund_request"),
    ("Need to return these unopened headphones — refund please.", "refund_request"),
    ("Hey, the headphones I bought last week are still sealed — can I return them for my money back?", "refund_request"),
    ("Please cancel order 99021 and refund my card. I no longer need it.", "refund_request"),
    ("Cancel order 99021 and refund the charge — I changed my mind.", "refund_request"),
    ("Please void order 99021 and put the money back on my card.", "refund_request"),
    ("Where is my refund? I returned the item two weeks ago and still nothing on my card.", "refund_request"),
    ("Returned the item two weeks ago, no refund yet — where is it?", "refund_request"),
    ("I sent the product back 14 days ago. My card still hasn't been credited. What's the holdup?", "refund_request"),
    ("I was charged $89 but the website showed $79 at checkout. Please refund the difference.", "refund_request"),
    ("Charged $89, but the site listed $79. Please refund the $10 difference.", "refund_request"),
    ("You overcharged me by $10. Please credit the difference back to my card.", "refund_request"),
    ("Returning these for store credit is fine but honestly I'd prefer cash back to my original card.", "refund_request"),
    ("Returning these — and please refund to my card, not store credit.", "refund_request"),
    ("Happy to return these but I'd rather get a real refund than store credit.", "refund_request"),
    ("I was double-charged on the same order. Please refund the duplicate transaction.", "refund_request"),
    ("There are two charges on my card for the same order. Please refund one.", "refund_request"),
    ("Card was hit twice for one order — please reverse the duplicate.", "refund_request"),
    ("The price dropped two days after I bought it. Can I get the difference back?", "refund_request"),
    ("Saw the same item dropped in price right after I bought it. Any way to get the difference?", "refund_request"),
    ("Item went on sale right after I ordered. Do you do price adjustments?", "refund_request"),
    ("Cancel my subscription and refund this month's charge — I never used it.", "refund_request"),
    ("Please cancel my subscription and refund this month — I haven't used the service.", "refund_request"),
    ("Subscription cancel + refund of this month, please. I haven't used it once.", "refund_request"),
    ("Your return window says 30 days. I missed it by 2 days. Refund anyway?", "refund_request"),
    ("I'm just past the 30-day return window — would you still take it back for a refund?", "refund_request"),
    ("Return window technically ended 2 days ago. Any chance of a refund?", "refund_request"),
    ("Disputing this charge with my bank — but I'd rather just get a refund directly from you.", "refund_request"),
    ("Was about to dispute with my bank — would rather just get refunded by you instead.", "refund_request"),
    ("Don't want to do a chargeback — please just refund me directly.", "refund_request"),
    ("The coffee maker arrived with a cracked carafe. Really disappointed.", "product_issue"),
    ("Coffee maker showed up with the carafe cracked. Not happy.", "product_issue"),
    ("The carafe on the coffee maker was already cracked when I opened the box.", "product_issue"),
    ("You sent me a size medium shirt but I ordered a large. Second time this has happened.", "product_issue"),
    ("Wrong size again — got a medium, ordered a large. This is twice now.", "product_issue"),
    ("I ordered a large shirt and you sent a medium. Second time this has happened.", "product_issue"),
    ("Item itself works fine but the box was crushed and the instruction manual is missing.", "product_issue"),
    ("Product works, but the box arrived crushed and there's no manual inside.", "product_issue"),
    ("Box was destroyed and the manual is missing. The actual product is fine though.", "product_issue"),
    ("It's defective — third one in a row from your store.", "product_issue"),
    ("Third defective unit from you — this one doesn't work either.", "product_issue"),
    ("Yet another defective product. Three for three from your store.", "product_issue"),
    ("My laptop arrived damaged and I want a full refund, not a replacement.", "refund_request"),
    ("Laptop showed up damaged. I want my money back, not a replacement.", "refund_request"),
    ("Damaged laptop on arrival — please refund me in full, no replacement.", "refund_request"),
    ("Sent the wrong color — I want my money back.", "refund_request"),
    ("Wrong color shipped. Refund please.", "refund_request"),
    ("You sent the wrong color. Just refund me.", "refund_request"),
    ("The product description said 'wireless' but I had to buy a separate dongle to use it. Misleading.", "product_issue"),
    ("Description claimed wireless. I had to buy a dongle separately. Felt misled.", "product_issue"),
    ("Item is technically wireless but only with a separate dongle, which the listing didn't mention.", "product_issue"),
    ("This pillow is way smaller than what the photos suggested. False advertising.", "product_issue"),
    ("Pillow is much smaller than the photos. Misleading.", "product_issue"),
    ("Got the pillow, it's tiny compared to the photos on the site.", "product_issue"),
    ("The blender stopped working after 3 days. Can I get a replacement?", "product_issue"),
    ("Blender died after three days of use. Replacement, please.", "product_issue"),
    ("My blender stopped working three days in — can you send a replacement?", "product_issue"),
    ("Item smells strongly of chemicals — definitely not okay to use around food.", "product_issue"),
    ("Strong chemical smell on the item. I wouldn't use this around food.", "product_issue"),
    ("Whatever you sent reeks of chemicals. Not food-safe.", "product_issue"),
    ("I can't log into my account — it keeps saying my password is wrong even after I reset it.", "account_help"),
    ("Password reset didn't help — still can't log in.", "account_help"),
    ("Login keeps saying wrong password even though I just reset it. Help.", "account_help"),
    ("How do I update the credit card on file? I don't see the option anywhere in settings.", "account_help"),
    ("I need to change my saved card. Can't find the setting.", "account_help"),
    ("Where do I update my credit card info? Settings don't show it.", "account_help"),
    ("Please remove my old shipping address. I moved last month and don't want stuff going there.", "account_help"),
    ("Drop my old shipping address from my account. Just moved.", "account_help"),
    ("Could you delete my previous shipping address? I don't want things sent there.", "account_help"),
    ("I keep getting 2FA codes I didn't request. Is someone trying to access my account?", "account_help"),
    ("2FA codes are showing up that I didn't ask for. Should I be worried?", "account_help"),
    ("Random 2FA codes are arriving by SMS. I didn't request any.", "account_help"),
    ("The website won't let me check out — it keeps logging me out mid-payment.", "account_help"),
    ("Site logs me out every time I try to pay.", "account_help"),
    ("Can't finish my purchase — keeps signing me out at the payment step.", "account_help"),
    ("Your app keeps crashing whenever I try to view my order history.", "account_help"),
    ("App crashes every time I open my order history.", "account_help"),
    ("Whenever I tap on my orders the app force-closes.", "account_help"),
    ("I forgot which email I used to sign up. How do I find my old account?", "account_help"),
    ("Don't remember which email my account is under. How do I look it up?", "account_help"),
    ("Lost track of the email I signed up with — can you help me find the account?", "account_help"),
    ("Need to change my account email to a different address — old one is dead.", "account_help"),
    ("Old email is gone — please switch my account to my new email.", "account_help"),
    ("My signup email is dead. I want to switch the account to a new one.", "account_help"),
    ("The discount code from your newsletter won't apply at checkout. Says 'invalid'.", "account_help"),
    ("Newsletter promo code is being rejected at checkout as invalid.", "account_help"),
    ("My promo code says 'invalid' even though I just got the newsletter.", "account_help"),
    ("Receipt email says I bought it, but the order isn't showing in my account.", "account_help"),
    ("Got a receipt by email but the order isn't in my account's order history.", "account_help"),
    ("Email says my purchase went through but I don't see the order in my account.", "account_help"),
    ("Do you guys ship to Canada? Couldn't find it on the FAQ page.", "other"),
    ("Quick question — do you ship to Canada?", "other"),
    ("Couldn't find shipping info on the site. Do you ship to Canada?", "other"),
    ("Just wanted to say the customer service rep I spoke to yesterday was amazing. Thank you!", "other"),
    ("Big thanks to your customer service team — yesterday's rep was great!", "other"),
    ("The rep I worked with yesterday was wonderful — please pass along my thanks.", "other"),
    ("Is the red version of SKU-1140 back in stock?", "other"),
    ("Restock alert? When will SKU-1140 in red be back?", "other"),
    ("Looking for the red SKU-1140 — is it available again yet?", "other"),
    ("Do you offer a student discount? Couldn't find one at checkout.", "other"),
    ("Any student-discount option? Didn't see one in checkout.", "other"),
    ("Is there a student discount on your store?", "other"),
    ("When's your next sale? My birthday is coming up and I'd love to splurge.", "other"),
    ("Got any sales coming up? Birthday is around the corner.", "other"),
    ("When does your next sale start? Want to time a big purchase.", "other"),
    ("Do you have a sustainability report or info on where your products are sourced?", "other"),
    ("Where do you source your products from? Curious about sustainability.", "other"),
    ("Any sustainability info available for your products?", "other"),
    ("Can I bulk-order 50 units? Looking for B2B pricing.", "other"),
    ("Need 50 units — do you offer B2B pricing?", "other"),
    ("Bulk order question — 50 units, any volume discount?", "other"),
    ("Why is shipping so expensive? Just feedback — not asking about a specific order.", "other"),
    ("Your shipping prices are wild. Just sharing feedback.", "other"),
    ("Shipping costs feel really high. Just venting, not about a specific order.", "other"),
    ("Are the AirPods you sell authentic Apple products?", "other"),
    ("Just want to make sure — the AirPods on your store are genuine Apple, right?", "other"),
    ("Are these AirPods real Apple gear or knock-offs?", "other"),
    ("Do you sell gift cards? Couldn't find them anywhere on the site.", "other"),
    ("Any gift cards available? Don't see them in the menu.", "other"),
    ("Do you offer gift cards?", "other"),
]

tickets = [
    {"id": f"t{i:03d}", "text": text, "true_category": label, "source": "golden"}
    for i, (text, label) in enumerate(GOLDEN_TICKETS)
]

print(f"Loaded {len(tickets)} tickets across {len(CATEGORIES)} categories.")
from collections import Counter
for cat, n in Counter(t["true_category"] for t in tickets).items():
    print(f"  {cat:>15}: {n}")
print()
for t in tickets[:5]:
    print(f"  [{t['true_category']:>15}] {t['text'][:90]}")

Loaded 150 tickets across 5 categories.
     order_status: 24
   refund_request: 42
    product_issue: 24
     account_help: 30
            other: 30

  [   order_status] Hi, I ordered a blender 5 days ago and the tracking page hasn't updated. Can you tell me w
  [   order_status] Hey, placed an order for a blender 5 days back and the tracking still shows nothing. Where
  [   order_status] So I ordered a blender on Monday, supposedly it shipped, but the tracking page is dead. Wh
  [   order_status] My package was supposed to arrive yesterday but it's still not here. Order #44812.
  [   order_status] Order #44812 was due yesterday and hasn't shown up. Any update?

## 5a. What OpenTelemetry adds here

LangSmith is the place where we inspect AI traces and compare baseline vs improved runs. OpenTelemetry is the standard way we emit structured traces from code.

In this notebook, we add one OpenTelemetry parent span around each ticket classification. The LangGraph / LangChain internals still create child spans for the model call, and the parent span carries eval metadata:

- `eval.example_id`: ticket id
- `eval.run_name`: baseline or improved
- `eval.prompt_version`: v1 or v2
- `eval.true_category`: ground-truth label
- `eval.predicted_category`: model output
- `eval.correct`: whether the prediction matched the label
- `eval.reasoning`: model explanation

This makes each row in the CSV traceable back to a specific LangSmith/OpenTelemetry run.

If you see `Failed to export span batch code: 404`, the classifier is still running, but the OTLP exporter is pointed at the wrong URL. This notebook clears stale `OTEL_EXPORTER_*` values and explicitly sends trace spans to `https://api.smith.langchain.com/otel/v1/traces`.

## 5. Build the LangGraph classification agent

LangGraph models an agent as a **graph of nodes**. For a classifier, the graph is tiny — one node that calls the LLM with a structured output schema. We're using LangGraph here (instead of just calling the LLM directly) so the pattern scales to multi-step agents later (e.g., add a retrieval node, a tool-calling node, a confidence-check node).

Because LangSmith tracing is on, **every graph invocation becomes a clickable trace** showing each node's input/output.

In [5]:
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from typing import TypedDict, Literal
from langgraph.graph import StateGraph, START, END
from langchain_core.prompts import ChatPromptTemplate

# --- THIS PROMPT IS WHAT YOU'LL TWEAK LATER ---
CLASSIFIER_PROMPT = """You are a triage system for an e-commerce support inbox.

Classify the customer's ticket into EXACTLY ONE of these categories:

- order_status: questions about where an order is, tracking, delivery ETA
- refund_request: the customer wants their money back
- product_issue: the item arrived broken, wrong, defective, or not as described
- account_help: login, password, address, payment method changes
- other: anything that doesn't fit the above (general questions, feedback, browsing)

Return only the category key.

Ticket:
{ticket_text}
"""

class Classification(BaseModel):
    category: Literal["order_status", "refund_request", "product_issue", "account_help", "other"]
    reasoning: str = Field(description="One short sentence explaining the choice.")

class AgentState(TypedDict):
    ticket_text: str
    category: str
    reasoning: str

def build_agent(prompt_template: str):
    """Compile a LangGraph agent. Re-call this any time you change the prompt."""
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0).with_structured_output(Classification)
    prompt = ChatPromptTemplate.from_template(prompt_template)

    def classify_node(state: AgentState) -> AgentState:
        result = (prompt | llm).invoke({"ticket_text": state["ticket_text"]})
        return {"ticket_text": state["ticket_text"], "category": result.category, "reasoning": result.reasoning}

    graph = StateGraph(AgentState)
    graph.add_node("classify", classify_node)
    graph.add_edge(START, "classify")
    graph.add_edge("classify", END)
    return graph.compile()

agent = build_agent(CLASSIFIER_PROMPT)

# Smoke test on one ticket.
sample = agent.invoke({"ticket_text": tickets[0]["text"], "category": "", "reasoning": ""})
print("Ticket:    ", tickets[0]["text"])
print("Predicted: ", sample["category"])
print("Reasoning: ", sample["reasoning"])

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/langgraph/cache/base/__init__.py:8: LangChainPendingDeprecationWarning: The default value of `allowed_objects` will change in a future version. Pass an explicit value (e.g., allowed_objects='messages' or allowed_objects='core') to suppress this warning.
  from langgraph.checkpoint.serde.jsonplus import JsonPlusSerializer

Ticket:     Hi, I ordered a blender 5 days ago and the tracking page hasn't updated. Can you tell me where it is?
Predicted:  order_status
Reasoning:  The customer is inquiring about the status and tracking of their order.

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...acking of their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(

In [6]:
from opentelemetry import trace

# This tracer creates ticket-level spans. LangSmith receives them because
# LANGSMITH_OTEL_ENABLED=true is set above.
tracer = trace.get_tracer("customer-support-evals")

## 6. Run the agent on every ticket

Each invocation is automatically traced in LangSmith. After this cell finishes, go to your [LangSmith dashboard](https://smith.langchain.com) → project **`customer-support-evals`** → and you'll see every prediction with full input/output/latency.

In [7]:
import pandas as pd
from tqdm import tqdm

def run_predictions(agent, tickets, run_name="baseline", prompt_version="v1") -> pd.DataFrame:
    rows = []
    for t in tqdm(tickets, desc=f"Classifying {run_name}"):
        # One parent span per ticket makes the spreadsheet row traceable in LangSmith.
        with tracer.start_as_current_span("customer_support.classify_ticket") as span:
            span.set_attribute("langsmith.span.kind", "chain")
            span.set_attribute("eval.run_name", run_name)
            span.set_attribute("eval.prompt_version", prompt_version)
            span.set_attribute("eval.example_id", t["id"])
            span.set_attribute("eval.true_category", t["true_category"])
            span.set_attribute("input.ticket_text", t["text"])

            out = agent.invoke({"ticket_text": t["text"], "category": "", "reasoning": ""})
            correct = t["true_category"] == out["category"]

            span.set_attribute("eval.predicted_category", out["category"])
            span.set_attribute("eval.correct", correct)
            span.set_attribute("eval.reasoning", out["reasoning"])
            span.set_attribute("output.category", out["category"])

            rows.append({
                "id": t["id"],
                "ticket_text": t["text"],
                "true_category": t["true_category"],
                "predicted_category": out["category"],
                "reasoning": out["reasoning"],
                "correct": correct,
                "otel_run_name": run_name,
                "otel_prompt_version": prompt_version,
            })
    return pd.DataFrame(rows)

results_v1 = run_predictions(agent, tickets, run_name="baseline", prompt_version="v1")
results_v1.head(10)

Classifying baseline:   0%|          | 0/150 [00:00<?, ?it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...acking of their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:   1%|          | 1/150 [00:00<01:34,  1.57it/s]

Classifying baseline:   1%|▏         | 2/150 [00:01<02:04,  1.19it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... tracking information.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:   2%|▏         | 3/150 [00:02<01:52,  1.31it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...rder and its delivery.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:   3%|▎         | 4/150 [00:03<01:56,  1.25it/s]

Classifying baseline:   3%|▎         | 5/150 [00:04<02:05,  1.15it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...livery of their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:   4%|▍         | 6/150 [00:05<02:27,  1.03s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... link for their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:   5%|▍         | 7/150 [00:06<02:12,  1.08it/s]

Classifying baseline:   5%|▌         | 8/150 [00:06<01:55,  1.23it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...cation of their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:   6%|▌         | 9/150 [00:07<01:46,  1.32it/s]

Classifying baseline:   7%|▋         | 10/150 [00:08<01:56,  1.20it/s]

Classifying baseline:   7%|▋         | 11/150 [00:09<01:46,  1.30it/s]

Classifying baseline:   8%|▊         | 12/150 [00:09<01:40,  1.37it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...t receive their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:   9%|▊         | 13/150 [00:10<01:39,  1.37it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...receiving their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:   9%|▉         | 14/150 [00:11<01:39,  1.37it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ceiving their package.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  10%|█         | 15/150 [00:11<01:37,  1.39it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ered but not received.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  11%|█         | 16/150 [00:12<01:39,  1.35it/s]

Classifying baseline:  11%|█▏        | 17/150 [00:13<01:33,  1.42it/s]

Classifying baseline:  12%|█▏        | 18/150 [00:13<01:30,  1.46it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... their order delivery.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  13%|█▎        | 19/150 [00:14<01:29,  1.46it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... its delayed delivery.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  13%|█▎        | 20/150 [00:15<01:26,  1.50it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...and its delivery time.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  14%|█▍        | 21/150 [00:15<01:22,  1.56it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...rder stuck in customs.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  15%|█▍        | 22/150 [00:16<01:23,  1.54it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... expedite the process.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  15%|█▌        | 23/150 [00:17<01:24,  1.51it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ry ETA of their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  16%|█▌        | 24/150 [00:18<01:34,  1.34it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ddress of their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  17%|█▋        | 25/150 [00:18<01:29,  1.39it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...lem with the delivery.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  17%|█▋        | 26/150 [00:19<01:24,  1.46it/s]

Classifying baseline:  18%|█▊        | 27/150 [00:19<01:23,  1.47it/s]

Classifying baseline:  19%|█▊        | 28/150 [00:20<01:21,  1.50it/s]

Classifying baseline:  19%|█▉        | 29/150 [00:21<01:20,  1.51it/s]

Classifying baseline:  20%|██        | 30/150 [00:22<01:24,  1.42it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... get their money back.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  21%|██        | 31/150 [00:22<01:23,  1.42it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...r unopened headphones.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  21%|██▏       | 32/150 [00:23<01:17,  1.51it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... an item for a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  22%|██▏       | 33/150 [00:24<01:19,  1.47it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...efund for their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  23%|██▎       | 34/150 [00:24<01:17,  1.50it/s]

Classifying baseline:  23%|██▎       | 35/150 [00:25<01:14,  1.54it/s]

Classifying baseline:  24%|██▍       | 36/150 [00:27<01:55,  1.01s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...tatus of their refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  25%|██▍       | 37/150 [00:27<01:39,  1.14it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...d for a returned item.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  25%|██▌       | 38/150 [00:28<01:29,  1.26it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...or a returned product.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  26%|██▌       | 39/150 [00:29<01:32,  1.20it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ence in price charged.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  27%|██▋       | 40/150 [00:30<01:29,  1.23it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...in the charged amount.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  27%|██▋       | 41/150 [00:30<01:25,  1.28it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...under refund requests.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  28%|██▊       | 42/150 [00:31<01:18,  1.37it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...o their original card.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  29%|██▊       | 43/150 [00:31<01:15,  1.42it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... refund to their card.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  29%|██▉       | 44/150 [00:32<01:10,  1.50it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...stead of store credit.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  30%|███       | 45/150 [00:33<01:10,  1.48it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...or a duplicate charge.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  31%|███       | 46/150 [00:33<01:09,  1.50it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...the duplicate charges.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  31%|███▏      | 47/150 [00:34<01:07,  1.54it/s]

Classifying baseline:  32%|███▏      | 48/150 [00:35<01:08,  1.48it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ce after a price drop.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  33%|███▎      | 49/150 [00:35<01:06,  1.51it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... the price difference.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  33%|███▎      | 50/150 [00:36<01:07,  1.48it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... specified categories.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  34%|███▍      | 51/150 [00:37<01:05,  1.50it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...to their subscription.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  35%|███▍      | 52/150 [00:38<01:09,  1.41it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...n they want to cancel.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  35%|███▌      | 53/150 [00:38<01:07,  1.44it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...on they have not used.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  36%|███▌      | 54/150 [00:39<01:06,  1.45it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ing the return window.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  37%|███▋      | 55/150 [00:40<01:05,  1.44it/s]

Classifying baseline:  37%|███▋      | 56/150 [00:40<01:02,  1.50it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ssibility of a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  38%|███▊      | 57/150 [00:41<01:00,  1.53it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ctly from the company.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  39%|███▊      | 58/150 [00:42<01:10,  1.30it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...harge with their bank.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  39%|███▉      | 59/150 [00:43<01:07,  1.34it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ing a refund directly.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  40%|████      | 60/150 [00:43<01:03,  1.41it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...e item arrived broken.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  41%|████      | 61/150 [00:44<00:59,  1.49it/s]

Classifying baseline:  41%|████▏     | 62/150 [00:44<00:58,  1.51it/s]

Classifying baseline:  42%|████▏     | 63/150 [00:45<00:54,  1.60it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...cates a product issue.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  43%|████▎     | 64/150 [00:46<00:55,  1.55it/s]

Classifying baseline:  43%|████▎     | 65/150 [00:46<00:55,  1.54it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ating a product issue.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  44%|████▍     | 66/150 [00:47<00:55,  1.52it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ged and missing parts.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  45%|████▍     | 67/150 [00:48<00:57,  1.45it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... and missing a manual.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  45%|████▌     | 68/150 [00:48<00:54,  1.51it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...e product's packaging."), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  46%|████▌     | 69/150 [00:50<01:15,  1.07it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...product they received.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  47%|████▋     | 70/150 [00:51<01:12,  1.10it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...received is defective.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  47%|████▋     | 71/150 [00:51<01:04,  1.23it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... product is defective.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  48%|████▊     | 72/150 [00:53<01:23,  1.07s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... for a damaged laptop.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  49%|████▊     | 73/150 [00:54<01:15,  1.02it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...nd for a damaged item.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  49%|████▉     | 74/150 [00:54<01:05,  1.15it/s]

Classifying baseline:  50%|█████     | 75/150 [00:55<01:00,  1.25it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...s requesting a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  51%|█████     | 76/150 [00:56<00:54,  1.36it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...iving the wrong color.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  51%|█████▏    | 77/150 [00:56<00:49,  1.46it/s]

Classifying baseline:  52%|█████▏    | 78/150 [00:57<00:50,  1.44it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...tionality of the item.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  53%|█████▎    | 79/150 [00:57<00:47,  1.49it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ith the item received.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  53%|█████▎    | 80/150 [00:58<00:45,  1.53it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ovided in the listing.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  54%|█████▍    | 81/150 [00:59<00:45,  1.51it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ons set by the photos.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  55%|█████▍    | 82/150 [01:00<00:46,  1.45it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...match the description.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  55%|█████▌    | 83/150 [01:00<00:46,  1.44it/s]

Classifying baseline:  56%|█████▌    | 84/150 [01:01<00:44,  1.48it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...hortly after purchase.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  57%|█████▋    | 85/150 [01:01<00:42,  1.52it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...uesting a replacement.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  57%|█████▋    | 86/150 [01:02<00:44,  1.45it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...hat arrived defective.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  58%|█████▊    | 87/150 [01:03<00:44,  1.43it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...efect or safety issue.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  59%|█████▊    | 88/150 [01:04<00:44,  1.39it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ssue with the product.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  59%|█████▉    | 89/150 [01:04<00:40,  1.50it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...blem with the product.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  60%|██████    | 90/150 [01:05<00:40,  1.47it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ng into their account.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  61%|██████    | 91/150 [01:06<00:38,  1.53it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ls under account help.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  61%|██████▏   | 92/150 [01:06<00:38,  1.53it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...eir login credentials.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  62%|██████▏   | 93/150 [01:08<01:00,  1.06s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... their payment method.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  63%|██████▎   | 94/150 [01:09<00:53,  1.05it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... saved payment method.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  63%|██████▎   | 95/150 [01:10<00:46,  1.18it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...to account management.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  64%|██████▍   | 96/150 [01:10<00:42,  1.28it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...heir shipping address.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  65%|██████▍   | 97/150 [01:11<00:42,  1.26it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ress in their account.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  65%|██████▌   | 98/150 [01:12<00:38,  1.35it/s]

Classifying baseline:  66%|██████▌   | 99/150 [01:12<00:36,  1.40it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...d needs help with 2FA.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  67%|██████▋   | 100/150 [01:13<00:35,  1.42it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...t security and access.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  67%|██████▋   | 101/150 [01:14<00:34,  1.41it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ecurity and 2FA codes.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  68%|██████▊   | 102/150 [01:14<00:33,  1.41it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...nd payment processing.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  69%|██████▊   | 103/150 [01:15<00:32,  1.45it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...g the payment process.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  69%|██████▉   | 104/150 [01:16<00:30,  1.51it/s]

Classifying baseline:  70%|███████   | 105/150 [01:16<00:29,  1.54it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...fically order history.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  71%|███████   | 106/150 [01:17<00:27,  1.59it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...g account information.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  71%|███████▏  | 107/150 [01:17<00:25,  1.69it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...to the user's account."), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  72%|███████▏  | 108/150 [01:18<00:24,  1.68it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...unt login information.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  73%|███████▎  | 109/150 [01:19<00:24,  1.69it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...h their account email.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  73%|███████▎  | 110/150 [01:19<00:23,  1.69it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...r account information.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  74%|███████▍  | 111/150 [01:20<00:23,  1.64it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...account email address.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  75%|███████▍  | 112/150 [01:20<00:24,  1.56it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...g their account email.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  75%|███████▌  | 113/150 [01:21<00:24,  1.54it/s]

Classifying baseline:  76%|███████▌  | 114/150 [01:22<00:23,  1.56it/s]

Classifying baseline:  77%|███████▋  | 115/150 [01:22<00:23,  1.51it/s]

Classifying baseline:  77%|███████▋  | 116/150 [01:23<00:22,  1.53it/s]

Classifying baseline:  78%|███████▊  | 117/150 [01:24<00:21,  1.53it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...eceived a receipt for.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  79%|███████▊  | 118/150 [01:24<00:21,  1.51it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...count's order history."), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  79%|███████▉  | 119/150 [01:25<00:20,  1.50it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...bility of their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  80%|████████  | 120/150 [01:26<00:19,  1.53it/s]

Classifying baseline:  81%|████████  | 121/150 [01:26<00:18,  1.57it/s]

Classifying baseline:  81%|████████▏ | 122/150 [01:27<00:18,  1.54it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...out shipping policies.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  82%|████████▏ | 123/150 [01:28<00:16,  1.61it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... the other categories.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  83%|████████▎ | 124/150 [01:28<00:16,  1.55it/s]

Classifying baseline:  83%|████████▎ | 125/150 [01:29<00:16,  1.53it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ific support category.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  84%|████████▍ | 126/150 [01:29<00:14,  1.62it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...rder or account issue.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  85%|████████▍ | 127/150 [01:30<00:14,  1.61it/s]

Classifying baseline:  85%|████████▌ | 128/150 [01:31<00:13,  1.58it/s]

Classifying baseline:  86%|████████▌ | 129/150 [01:31<00:12,  1.62it/s]

Classifying baseline:  87%|████████▋ | 130/150 [01:32<00:12,  1.66it/s]

Classifying baseline:  87%|████████▋ | 131/150 [01:32<00:10,  1.74it/s]

Classifying baseline:  88%|████████▊ | 132/150 [01:33<00:10,  1.73it/s]

Classifying baseline:  89%|████████▊ | 133/150 [01:34<00:10,  1.70it/s]

Classifying baseline:  89%|████████▉ | 134/150 [01:34<00:09,  1.68it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ssue, or account help.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  90%|█████████ | 135/150 [01:35<00:10,  1.44it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ts, or account issues.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  91%|█████████ | 136/150 [01:36<00:09,  1.45it/s]

Classifying baseline:  91%|█████████▏| 137/150 [01:36<00:08,  1.49it/s]

Classifying baseline:  92%|█████████▏| 138/150 [01:37<00:07,  1.54it/s]

Classifying baseline:  93%|█████████▎| 139/150 [01:38<00:07,  1.51it/s]

Classifying baseline:  93%|█████████▎| 140/150 [01:38<00:06,  1.50it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...sues, or account help.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  94%|█████████▍| 141/150 [01:39<00:06,  1.47it/s]

Classifying baseline:  95%|█████████▍| 142/150 [01:40<00:05,  1.51it/s]

Classifying baseline:  95%|█████████▌| 143/150 [01:41<00:04,  1.46it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...d to a specific order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  96%|█████████▌| 144/150 [01:41<00:04,  1.45it/s]

Classifying baseline:  97%|█████████▋| 145/150 [01:42<00:03,  1.51it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... product authenticity.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying baseline:  97%|█████████▋| 146/150 [01:42<00:02,  1.57it/s]

Classifying baseline:  98%|█████████▊| 147/150 [01:43<00:02,  1.48it/s]

Classifying baseline:  99%|█████████▊| 148/150 [01:44<00:01,  1.38it/s]

Classifying baseline:  99%|█████████▉| 149/150 [01:45<00:00,  1.39it/s]

Classifying baseline: 100%|██████████| 150/150 [01:45<00:00,  1.40it/s]

Classifying baseline: 100%|██████████| 150/150 [01:45<00:00,  1.42it/s]

,id,ticket_text,true_category,predicted_category,reasoning,correct,otel_run_name,otel_prompt_version
0,t000,"Hi, I ordered a blender 5 days ago and the tra...",order_status,order_status,The customer is inquiring about the status and...,True,baseline,v1
1,t001,"Hey, placed an order for a blender 5 days back...",order_status,order_status,The customer is inquiring about the status and...,True,baseline,v1
2,t002,"So I ordered a blender on Monday, supposedly i...",order_status,order_status,The customer is inquiring about the status of ...,True,baseline,v1
3,t003,My package was supposed to arrive yesterday bu...,order_status,order_status,The customer is inquiring about the status of ...,True,baseline,v1
4,t004,Order #44812 was due yesterday and hasn't show...,order_status,order_status,The customer is inquiring about the status of ...,True,baseline,v1
5,t005,Where's my package? Was supposed to arrive yes...,order_status,order_status,The customer is inquiring about the status and...,True,baseline,v1
6,t006,Tracking link in the email just spins forever....,order_status,order_status,The customer is inquiring about the tracking l...,True,baseline,v1
7,t007,"Hey, the tracking link you emailed me for orde...",order_status,order_status,The customer is inquiring about the tracking l...,True,baseline,v1
8,t008,Tracking URL is broken. Order 88421. Can you t...,order_status,order_status,The customer is inquiring about the status and...,True,baseline,v1
9,t009,Order shows delivered last Tuesday but it's no...,order_status,order_status,The customer is inquiring about the status of ...,True,baseline,v1

## 7. Evaluate: accuracy, precision, recall

- **Accuracy** = fraction of tickets classified correctly overall.
- **Precision (per class)** = of all the tickets the model *called* `refund_request`, how many actually were? High precision = few false alarms.
- **Recall (per class)** = of all the tickets that *truly were* `refund_request`, how many did the model catch? High recall = few misses.

**Why look at both:** a model that *always* predicts `other` will have 20% accuracy and 100% recall on `other` but 0% recall on everything else. Per-class precision/recall exposes that immediately.

In [8]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def evaluate(df: pd.DataFrame, label: str):
    y_true = df["true_category"]
    y_pred = df["predicted_category"]
    print(f"=== {label} ===")
    print(f"Accuracy: {accuracy_score(y_true, y_pred):.2%}  ({df['correct'].sum()}/{len(df)} correct)\n")
    print("Per-class precision / recall / F1:")
    print(classification_report(y_true, y_pred, labels=CATEGORIES, zero_division=0))
    print("Confusion matrix (rows = true, cols = predicted):")
    cm = pd.DataFrame(
        confusion_matrix(y_true, y_pred, labels=CATEGORIES),
        index=CATEGORIES, columns=CATEGORIES,
    )
    print(cm)
    return accuracy_score(y_true, y_pred)

acc_v1 = evaluate(results_v1, "Run 1 — baseline prompt")

=== Run 1 — baseline prompt ===
Accuracy: 96.67%  (145/150 correct)

Per-class precision / recall / F1:
                precision    recall  f1-score   support

  order_status       1.00      0.96      0.98        24
refund_request       1.00      0.98      0.99        42
 product_issue       0.96      1.00      0.98        24
  account_help       1.00      0.90      0.95        30
         other       0.88      1.00      0.94        30

      accuracy                           0.97       150
     macro avg       0.97      0.97      0.97       150
  weighted avg       0.97      0.97      0.97       150

Confusion matrix (rows = true, cols = predicted):
                order_status  refund_request  product_issue  account_help  \
order_status              23               0              1             0
refund_request             0              41              0             0
product_issue              0               0             24             0
account_help               0               0              0            27
other                      0               0              0             0

                other
order_status        0
refund_request      1
product_issue       0
account_help        3
other              30

## 8. Export to spreadsheet for validator comments

This is the **human-in-the-loop** step. Open `results_v1.csv` in Google Sheets or Excel.

Each row has an empty `validator_comment` column. Your job:

1. **Filter `correct == FALSE`** to see only the failures.
2. For each failure, write a short note in `validator_comment` — e.g. *"complaint about delivery, model called it product_issue"*, *"ambiguous, I'd accept either"*, *"label is wrong, this really is `other`"*.
3. Also scan a sample of `correct == TRUE` rows — sometimes the model gets the right label for the *wrong reason*.
4. Once you've annotated, **cluster the comments into 2–4 failure categories** in a separate tab. For example:
   - *"Confuses `order_status` with `refund_request` when the customer mentions both delivery and money"*
   - *"Calls polite thank-you messages `account_help`"*
   - *"Routes 'wrong item' as `refund_request` instead of `product_issue`"*
5. **Pick the one failure category that matters most for your use case** (the one that's most expensive if it happens in production), and bring it back to step 9.

In [9]:
results_v1_export = results_v1.copy()
results_v1_export["validator_comment"] = ""
results_v1_export["failure_category"] = ""
results_v1_export.to_csv("results_v1.csv", index=False)
print("Wrote results_v1.csv — open it in Google Sheets or Excel.")
print("Columns:", list(results_v1_export.columns))

Wrote results_v1.csv — open it in Google Sheets or Excel.
Columns: ['id', 'ticket_text', 'true_category', 'predicted_category', 'reasoning', 'correct', 'otel_run_name', 'otel_prompt_version', 'validator_comment', 'failure_category']

## 9. Tweak the prompt to fix the failure category you picked

Edit `IMPROVED_PROMPT` below to address the failure you chose. Some common moves:

- **Add disambiguation rules.** *"If the customer mentions both delivery delay AND a refund request, classify as `order_status` — the refund is downstream of the delivery problem."*
- **Add a few-shot example** of the exact failure case with the correct label.
- **Tighten a category definition.** *"`account_help` is ONLY for login/password/profile issues, not for general site bugs."*
- **Force a step.** *"First identify the customer's primary intent in one sentence, then pick the category."*

Keep the change focused on the **one failure category** you picked. If you change everything, you won't know what helped.

In [10]:
IMPROVED_PROMPT = """You are a triage system for an e-commerce support inbox.

Classify the customer's ticket into EXACTLY ONE of these categories:
- order_status: questions about where an order is, tracking, delivery ETA, or an order that is late, missing, or never arrived
- refund_request: the customer wants their money back
- product_issue: the item arrived broken, wrong, defective, or not as described
- account_help: login, password, address, payment method changes
- other: anything that doesn't fit the above (general questions, feedback, browsing)

HOW TO CLASSIFY
Classify by the ACTION the customer is asking you to take, not by the nouns that appear while they explain what happened. The words "order," "delivered," "package," "shipping," and "address" almost always appear in the customer's backstory. Backstory is context, not the request. Find the sentence where the customer states what they want done, and classify on that sentence.

Apply these in order. First match wins.

1. If the customer asks for a refund, money back, reimbursement, a credit, or to be charged back, classify as refund_request. This holds even when the ticket also describes a late delivery, a missing package, a damaged item, or an address. The delivery problem is why they want a refund; the refund is what they are asking you to do.

2. If the customer's order is late, missing, stuck in transit, or never arrived, and they have NOT asked for money back, classify as order_status. This holds even when the ticket mentions their address while explaining what happened. A customer describing a past delivery that went wrong is NOT asking you to update their account.

3. Use account_help ONLY when the customer is asking you to change or correct account information going forward: reset a password, fix a login, update the address or payment method on file for future orders. If the address is mentioned as part of explaining a delivery that already failed, it is order_status, not account_help.

4. If the item arrived broken, wrong, or not as described and no refund is requested, classify as product_issue.

EXAMPLES

Ticket: "Order #48812 was marked delivered to my address on the 3rd but I never got it. I've checked with neighbors and the building office. I'd like a refund at this point."
Answer: refund_request

Ticket: "Order #48812 was marked delivered to my address on the 3rd but nothing showed up. I've checked with my neighbors. Can you find out what happened to it?"
Answer: order_status

Ticket: "I just moved. Can you update the shipping address on my account so my next order goes to the new place?"
Answer: account_help

Return only the category key.

Ticket:
{ticket_text}
"""

agent_v2 = build_agent(IMPROVED_PROMPT)
results_v2 = run_predictions(agent_v2, tickets, run_name="improved", prompt_version="v2")

results_v2_export = results_v2.copy()
results_v2_export["validator_comment"] = ""
results_v2_export["failure_category"] = ""
results_v2_export.to_csv("results_v2.csv", index=False)

acc_v2 = evaluate(results_v2, "Run 2 — improved prompt")

Classifying improved:   0%|          | 0/150 [00:00<?, ?it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...status of their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   1%|          | 1/150 [00:00<02:08,  1.16it/s]

Classifying improved:   1%|▏         | 2/150 [00:01<02:00,  1.23it/s]

Classifying improved:   2%|▏         | 3/150 [00:02<02:00,  1.22it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... that has not arrived.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   3%|▎         | 4/150 [00:03<01:58,  1.23it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...pdate on a late order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   3%|▎         | 5/150 [00:04<02:30,  1.04s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...atus of their package.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   4%|▍         | 6/150 [00:05<02:18,  1.04it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...s, refund, or account.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   5%|▍         | 7/150 [00:06<02:18,  1.03it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...with the order status.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   5%|▌         | 8/150 [00:07<02:13,  1.06it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...tion of their package.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   6%|▌         | 9/150 [00:08<02:08,  1.10it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...t their missing order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   7%|▋         | 10/150 [00:09<02:10,  1.07it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ivered but is missing.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   7%|▋         | 11/150 [00:10<02:09,  1.07it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...g their missing order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   8%|▊         | 12/150 [00:10<02:02,  1.12it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...want their money back.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   9%|▊         | 13/150 [00:11<02:04,  1.10it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ly asked for a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:   9%|▉         | 14/150 [00:13<02:36,  1.15s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...es they want a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  10%|█         | 15/150 [00:15<02:56,  1.30s/it]

Classifying improved:  11%|█         | 16/150 [00:16<02:33,  1.14s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ge not being received.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  11%|█▏        | 17/150 [00:16<02:21,  1.06s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...y asking for a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  12%|█▏        | 18/150 [00:18<02:25,  1.10s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... order due to a delay.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  13%|█▎        | 19/150 [00:19<02:17,  1.05s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...t requesting a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  13%|█▎        | 20/150 [00:19<02:08,  1.01it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... order, which is late.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  14%|█▍        | 21/150 [00:20<02:04,  1.04it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...item stuck in customs.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  15%|█▍        | 22/150 [00:21<01:56,  1.10it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...order held by customs.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  15%|█▌        | 23/150 [00:22<01:47,  1.18it/s]

Classifying improved:  16%|█▌        | 24/150 [00:23<01:43,  1.22it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...t asking for a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  17%|█▋        | 25/150 [00:23<01:46,  1.17it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...tion on what happened.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  17%|█▋        | 26/150 [00:24<01:48,  1.14it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... unrecognized address."), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  18%|█▊        | 27/150 [00:26<02:08,  1.04s/it]

Classifying improved:  19%|█▊        | 28/150 [00:27<01:55,  1.05it/s]

Classifying improved:  19%|█▉        | 29/150 [00:27<01:45,  1.14it/s]

Classifying improved:  20%|██        | 30/150 [00:28<01:43,  1.16it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... get their money back.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  21%|██        | 31/150 [00:29<01:39,  1.19it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...e unopened headphones.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  21%|██▏       | 32/150 [00:30<01:35,  1.24it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... for their money back.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  22%|██▏       | 33/150 [00:30<01:35,  1.23it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...efund for their order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  23%|██▎       | 34/150 [00:31<01:37,  1.19it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...g to cancel the order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  23%|██▎       | 35/150 [00:32<01:33,  1.22it/s]

Classifying improved:  24%|██▍       | 36/150 [00:33<01:28,  1.29it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ter returning an item.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  25%|██▍       | 37/150 [00:34<01:29,  1.26it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...for the returned item.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  25%|██▌       | 38/150 [00:35<01:33,  1.20it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...r returning a product.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  26%|██▌       | 39/150 [00:35<01:33,  1.18it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... difference in charge.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  27%|██▋       | 40/150 [00:36<01:34,  1.17it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...of the $10 difference.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  27%|██▋       | 41/150 [00:37<01:34,  1.15it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... to being overcharged.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  28%|██▊       | 42/150 [00:38<01:34,  1.15it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... request for a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  29%|██▊       | 43/150 [00:39<01:37,  1.10it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... refund to their card.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  29%|██▉       | 44/150 [00:40<01:36,  1.09it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...stead of store credit.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  30%|███       | 45/150 [00:41<01:32,  1.14it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... being double-charged.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  31%|███       | 46/150 [00:42<01:27,  1.19it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...the duplicate charges.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  31%|███▏      | 47/150 [00:42<01:25,  1.21it/s]

Classifying improved:  32%|███▏      | 48/150 [00:43<01:22,  1.23it/s]

Classifying improved:  33%|███▎      | 49/150 [00:44<01:23,  1.20it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... the price difference.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  33%|███▎      | 50/150 [00:45<01:18,  1.27it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... specified categories.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  34%|███▍      | 51/150 [00:47<01:53,  1.14s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...refund for the charge.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  35%|███▍      | 52/150 [00:47<01:40,  1.02s/it]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...for the current month.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  35%|███▌      | 53/150 [00:48<01:28,  1.10it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... month's subscription."), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  36%|███▌      | 54/150 [00:49<01:23,  1.15it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ing the return window.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  37%|███▋      | 55/150 [00:50<01:19,  1.20it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ast the return window.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  37%|███▋      | 56/150 [00:50<01:15,  1.25it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...s asking for a refund.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  38%|███▊      | 57/150 [00:51<01:12,  1.29it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...for a refund directly.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  39%|███▊      | 58/150 [00:52<01:13,  1.25it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...uting with their bank.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  39%|███▉      | 59/150 [00:53<01:14,  1.23it/s]

Classifying improved:  40%|████      | 60/150 [00:53<01:10,  1.27it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ken item that arrived.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  41%|████      | 61/150 [00:54<01:13,  1.21it/s]

Classifying improved:  41%|████▏     | 62/150 [00:55<01:10,  1.25it/s]

Classifying improved:  42%|████▏     | 63/150 [00:56<01:12,  1.20it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ing a recurring issue.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  43%|████▎     | 64/150 [00:57<01:09,  1.23it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...blem with the product.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  43%|████▎     | 65/150 [00:58<01:08,  1.24it/s]

Classifying improved:  44%|████▍     | 66/150 [00:58<01:06,  1.26it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...o refund is requested.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  45%|████▍     | 67/150 [00:59<01:05,  1.26it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ating a product issue.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  45%|████▌     | 68/150 [01:01<01:27,  1.06s/it]

Classifying improved:  46%|████▌     | 69/150 [01:02<01:20,  1.01it/s]

Classifying improved:  47%|████▋     | 70/150 [01:02<01:14,  1.07it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...tem arrived defective.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  47%|████▋     | 71/150 [01:03<01:10,  1.12it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... product is defective.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  48%|████▊     | 72/150 [01:04<01:06,  1.18it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...or the damaged laptop.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  49%|████▊     | 73/150 [01:05<01:02,  1.23it/s]

Classifying improved:  49%|████▉     | 74/150 [01:05<01:00,  1.26it/s]

Classifying improved:  50%|█████     | 75/150 [01:06<00:59,  1.26it/s]

Classifying improved:  51%|█████     | 76/150 [01:07<01:01,  1.21it/s]

Classifying improved:  51%|█████▏    | 77/150 [01:08<00:55,  1.32it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...iving the wrong color.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  52%|█████▏    | 78/150 [01:09<00:55,  1.30it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... was not as described.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  53%|█████▎    | 79/150 [01:09<00:53,  1.32it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ith the item received.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  53%|█████▎    | 80/150 [01:10<00:56,  1.24it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...cribed in the listing.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  54%|█████▍    | 81/150 [01:11<00:55,  1.24it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...m is not as described.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  55%|█████▍    | 82/150 [01:12<00:53,  1.28it/s]

Classifying improved:  55%|█████▌    | 83/150 [01:13<00:52,  1.27it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ption or expectations.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  56%|█████▌    | 84/150 [01:13<00:52,  1.25it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... item being defective.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  57%|█████▋    | 85/150 [01:14<00:52,  1.24it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ent for a broken item.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  57%|█████▋    | 86/150 [01:15<00:47,  1.35it/s]

Classifying improved:  58%|█████▊    | 87/150 [01:16<00:47,  1.34it/s]

Classifying improved:  59%|█████▊    | 88/150 [01:16<00:43,  1.41it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...strong chemical smell.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  59%|█████▉    | 89/150 [01:17<00:44,  1.36it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...d has safety concerns.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  60%|██████    | 90/150 [01:18<00:44,  1.34it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ng into their account.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  61%|██████    | 91/150 [01:18<00:44,  1.32it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ith their login issue.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  61%|██████▏   | 92/150 [01:20<00:49,  1.18it/s]

Classifying improved:  62%|██████▏   | 93/150 [01:20<00:44,  1.27it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ayment method on file.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  63%|██████▎   | 94/150 [01:21<00:52,  1.06it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... saved payment method.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  63%|██████▎   | 95/150 [01:22<00:48,  1.12it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...edit card information.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  64%|██████▍   | 96/150 [01:23<00:46,  1.17it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ess for future orders.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  65%|██████▍   | 97/150 [01:24<00:41,  1.27it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...heir shipping address.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  65%|██████▌   | 98/150 [01:24<00:41,  1.25it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... the shipping address.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  66%|██████▌   | 99/150 [01:25<00:41,  1.24it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ated to their account.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  67%|██████▋   | 100/150 [01:26<00:40,  1.22it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ing a specific action.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  67%|██████▋   | 101/150 [01:27<00:38,  1.28it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...s to account security.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  68%|██████▊   | 102/150 [01:28<00:39,  1.21it/s]

Classifying improved:  69%|██████▊   | 103/150 [01:29<00:39,  1.19it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ue related to payment.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  69%|██████▉   | 104/150 [01:29<00:38,  1.20it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...o complete a purchase.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  70%|███████   | 105/150 [01:30<00:39,  1.13it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...account functionality.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  71%|███████   | 106/150 [01:31<00:35,  1.23it/s]

Classifying improved:  71%|███████▏  | 107/150 [01:32<00:34,  1.26it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...count's functionality."), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  72%|███████▏  | 108/150 [01:33<00:33,  1.25it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ifying the email used.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  73%|███████▎  | 109/150 [01:34<00:34,  1.19it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...p their account email.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  73%|███████▎  | 110/150 [01:34<00:32,  1.24it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...r account information.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  74%|███████▍  | 111/150 [01:35<00:29,  1.33it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...e their account email.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  75%|███████▍  | 112/150 [01:36<00:27,  1.36it/s]

Classifying improved:  75%|███████▌  | 113/150 [01:37<00:28,  1.30it/s]

Classifying improved:  76%|███████▌  | 114/150 [01:37<00:26,  1.34it/s]

Classifying improved:  77%|███████▋  | 115/150 [01:38<00:29,  1.18it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...o an order or account.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  77%|███████▋  | 116/150 [01:39<00:30,  1.12it/s]

Classifying improved:  78%|███████▊  | 117/150 [01:40<00:29,  1.13it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... order is not showing.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  79%|███████▊  | 118/150 [01:41<00:28,  1.11it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...g their order history.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  79%|███████▉  | 119/150 [01:42<00:26,  1.15it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ount to see the order.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  80%|████████  | 120/150 [01:43<00:23,  1.25it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...g any specific action.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  81%|████████  | 121/150 [01:43<00:21,  1.35it/s]

Classifying improved:  81%|████████▏ | 122/150 [01:44<00:22,  1.27it/s]

Classifying improved:  82%|████████▏ | 123/150 [01:45<00:20,  1.29it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...r any specific action.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  83%|████████▎ | 124/150 [01:45<00:18,  1.37it/s]

Classifying improved:  83%|████████▎ | 125/150 [01:46<00:19,  1.26it/s]

Classifying improved:  84%|████████▍ | 126/150 [01:47<00:19,  1.25it/s]

Classifying improved:  85%|████████▍ | 127/150 [01:48<00:18,  1.25it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... product availability.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  85%|████████▌ | 128/150 [01:49<00:16,  1.32it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... the other categories.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  86%|████████▌ | 129/150 [01:49<00:15,  1.35it/s]

Classifying improved:  87%|████████▋ | 130/150 [01:50<00:16,  1.21it/s]

Classifying improved:  87%|████████▋ | 131/150 [01:51<00:16,  1.18it/s]

Classifying improved:  88%|████████▊ | 132/150 [01:52<00:13,  1.29it/s]

Classifying improved:  89%|████████▊ | 133/150 [01:53<00:13,  1.29it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...is a general question.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  89%|████████▉ | 134/150 [01:53<00:12,  1.24it/s]

Classifying improved:  90%|█████████ | 135/150 [01:54<00:11,  1.34it/s]

Classifying improved:  91%|█████████ | 136/150 [01:55<00:10,  1.32it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ng and sustainability.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  91%|█████████▏| 137/150 [01:56<00:10,  1.27it/s]

Classifying improved:  92%|█████████▏| 138/150 [01:57<00:09,  1.27it/s]

Classifying improved:  93%|█████████▎| 139/150 [01:57<00:08,  1.24it/s]

Classifying improved:  93%|█████████▎| 140/150 [01:58<00:08,  1.24it/s]

Classifying improved:  94%|█████████▍| 141/150 [02:00<00:10,  1.16s/it]

Classifying improved:  95%|█████████▍| 142/150 [02:01<00:08,  1.04s/it]

Classifying improved:  95%|█████████▌| 143/150 [02:02<00:06,  1.03it/s]

Classifying improved:  96%|█████████▌| 144/150 [02:03<00:05,  1.06it/s]

Classifying improved:  97%|█████████▋| 145/150 [02:03<00:04,  1.13it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='... requesting an action.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  97%|█████████▋| 146/150 [02:04<00:03,  1.14it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ticity of the product.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  98%|█████████▊| 147/150 [02:05<00:02,  1.23it/s]

/Users/arsegas2/Projects/Lesson4/.venv/lib/python3.9/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `none` - serialized value may not be as expected [field_name='parsed', input_value=Classification(category='...ability of gift cards.'), input_type=Classification])
  return self.__pydantic_serializer__.to_python(
Classifying improved:  99%|█████████▊| 148/150 [02:06<00:01,  1.25it/s]

Classifying improved:  99%|█████████▉| 149/150 [02:06<00:00,  1.28it/s]

Classifying improved: 100%|██████████| 150/150 [02:08<00:00,  1.01s/it]

Classifying improved: 100%|██████████| 150/150 [02:08<00:00,  1.17it/s]

=== Run 2 — improved prompt ===
Accuracy: 96.00%  (144/150 correct)

Per-class precision / recall / F1:
                precision    recall  f1-score   support

  order_status       1.00      0.96      0.98        24
refund_request       1.00      0.98      0.99        42
 product_issue       1.00      1.00      1.00        24
  account_help       1.00      0.87      0.93        30
         other       0.83      1.00      0.91        30

      accuracy                           0.96       150
     macro avg       0.97      0.96      0.96       150
  weighted avg       0.97      0.96      0.96       150

Confusion matrix (rows = true, cols = predicted):
                order_status  refund_request  product_issue  account_help  \
order_status              23               0              0             0
refund_request             0              41              0             0
product_issue              0               0             24             0
account_help               0               0              0            26
other                      0               0              0             0

                other
order_status        1
refund_request      1
product_issue       0
account_help        4
other              30

## 10. Compare the two runs

Now look at the headline accuracy and at *which specific tickets flipped* between runs. Some will go from wrong → right (the win you were aiming for). Some may go from right → wrong (a regression you caused). This is normal — almost no prompt change is strictly Pareto-better, and the trade-offs are the most important thing to understand.

In [11]:
print(f"Accuracy v1: {acc_v1:.2%}")
print(f"Accuracy v2: {acc_v2:.2%}")
print(f"Δ          : {(acc_v2 - acc_v1):+.2%}\n")

comparison = results_v1.merge(
    results_v2[["id", "predicted_category", "reasoning", "correct"]],
    on="id", suffixes=("_v1", "_v2"),
)

flipped = comparison[comparison["predicted_category_v1"] != comparison["predicted_category_v2"]]
print(f"{len(flipped)} tickets changed prediction between runs.\n")

wins   = flipped[(~flipped["correct_v1"]) & (flipped["correct_v2"])]
losses = flipped[(flipped["correct_v1"]) & (~flipped["correct_v2"])]
print(f"Wins (wrong → right):     {len(wins)}")
print(f"Regressions (right → wrong): {len(losses)}")

flipped[["ticket_text", "true_category", "predicted_category_v1", "predicted_category_v2"]]

Accuracy v1: 96.67%
Accuracy v2: 96.00%
Δ          : -0.67%

3 tickets changed prediction between runs.

Wins (wrong → right):     1
Regressions (right → wrong): 2

,ticket_text,true_category,predicted_category_v1,predicted_category_v2
6,Tracking link in the email just spins forever....,order_status,order_status,other
25,Carrier delivered to the wrong address. The ad...,order_status,product_issue,order_status
100,2FA codes are showing up that I didn't ask for...,account_help,account_help,other

## 11. What to take away

- **LangGraph** gave us a clean shape for the agent. Right now it's one node, but you can drop in retrieval, tools, or a self-check node without rewriting the eval harness.
- **LangSmith** turned every LLM call into an inspectable trace. OpenTelemetry added a standard parent span around each ticket so CSV rows, prompt versions, labels, and correctness are attached to the trace.
- **Accuracy alone is a trap.** Per-class precision/recall and the confusion matrix tell you *what kind* of mistakes the model is making.
- **Validator comments are the most valuable artifact in this whole notebook.** Numbers tell you *that* something is wrong; human notes tell you *what* and *why*.
- **Prompt iteration is a measure → diagnose → fix → re-measure loop.** Without the dataset and the metrics, prompt tweaks are just vibes.

### Suggested next steps
- Replace the synthetic seed tickets with anonymized **real** tickets from your inbox.
- Upload the dataset to LangSmith as a versioned **Dataset** and use the LangSmith `evaluate()` runner so each prompt version gets a saved score.
- Add a second node to the graph — e.g., a confidence check that routes low-confidence predictions to a human queue.